### ISSUE TITLE
nonhermetic input

### ISSUE THREAD

**Issue by Skarlett** [QuantumCoded/nixos#1]
https://github.com/QuantumCoded/nixos/blob/c2f4d20bb8970f9fb7c1ed93f68b7893c0ce921d/flake.nix#L6

use `github:nixos/nixpkgs/nixpkgs-unstable` the current implementation is tied to your OS channels.

**Comment by QuantumCoded** [comment]
fixed in ecb780e

**Comment by QuantumCoded** [comment]
This issue is pointed to by the relative URL of an internal PR. If you got here from a hyperlink, this is likely not what you're looking for.
