### ISSUE TITLE
breaks upon usage

### ISSUE THREAD

**Issue by Skarlett** [QuantumCoded/nixos#2]
https://github.com/QuantumCoded/nixos/blob/c2f4d20bb8970f9fb7c1ed93f68b7893c0ce921d/flake.nix#L26

instead of passing `system` into `specialArgs` use `pkgs.stdenv.hostPlatform.system` to return what arch `pkgs` was initialized to use

using `{system, config, lib, pkgs, ...}` will cause nix to reject the build.

note: in
https://github.com/QuantumCoded/nixos/blob/master/overlays.nix#L1

nix doesn't reject the build because `system` is never evaluated.

foot-note: `system` overlaps an existing identifier

**Comment by Skarlett** [comment]
nvm it does build in this case, but be careful with that

**Comment by QuantumCoded** [comment]
fixed in 5979a41
